blobs = db.blobs.find({}, {hash: 1}).toArray();

db.users.insertMany([
  { login: "gilewski",    name: "Gerard Gilewski",     gender: "m", image_hash: blobs[0].hash}, 
  { login: "zwolinski",   name: "Rafał Zwoliński",     gender: "m", image_hash: blobs[1].hash}, 
  { login: "peters",      name: "Hanna Peters",        gender: "f", image_hash: blobs[2].hash}, 
  { login: "wojs",        name: "Malwina Wójs",        gender: "f", image_hash: blobs[3].hash}, 
  { login: "roslon",      name: "Seweryn Rosłon",      gender: "m", image_hash: blobs[4].hash}, 
  { login: "płaczek",     name: "Bogusław Płaczek",    gender: "m", image_hash: blobs[5].hash}, 
  { login: "zdzieblo",    name: "Kinga Zdziebło",      gender: "f", image_hash: blobs[6].hash}, 
  { login: "pol",         name: "Stefan Pol",          gender: "m", image_hash: blobs[7].hash}, 
  { login: "jakubaszek",  name: "Marian Jakubaszek",   gender: "m", image_hash: blobs[8].hash}, 
  { login: "gasiorek",    name: "Dominik Gąsiorek",    gender: "m", image_hash: blobs[9].hash}, 
  { login: "kunka",       name: "Julian Kunka",        gender: "m", image_hash: blobs[10].hash}, 
  { login: "kaja",        name: "Edward Kaja",         gender: "m", image_hash: blobs[11].hash}, 
  { login: "wojtaszczyk", name: "Marek Wojtaszczyk",   gender: "m", image_hash: blobs[12].hash}, 
  { login: "wosiak",      name: "Bogumił Wosiak",      gender: "m", image_hash: blobs[13].hash}, 
  { login: "dabkowski",   name: "Maksym Dąbkowski",    gender: "m", image_hash: blobs[14].hash}, 
  { login: "treder",      name: "Apolonia Treder",     gender: "f", image_hash: blobs[15].hash}, 
  { login: "gumkowski",   name: "Ignacy Gumkowski",    gender: "m", image_hash: blobs[16].hash}, 
  { login: "romanczuk",   name: "Beata Romańczuk",     gender: "f", image_hash: blobs[17].hash}, 
  { login: "pupek",       name: "Fryderyk Pupek",      gender: "m", image_hash: blobs[18].hash}, 
  { login: "silska",      name: "Lucyna Silska",       gender: "f", image_hash: blobs[19].hash}, 
  { login: "sielski",     name: "Mieczysław Sielski",  gender: "m", image_hash: blobs[20].hash}, 
  { login: "pylypenko",   name: "Lucyna Pylypenko",    gender: "f", image_hash: blobs[21].hash}, 
  { login: "pogodzinska", name: "Agata Pogodzińska",   gender: "f", image_hash: blobs[22].hash}, 
  { login: "kusmierski",  name: "Maciej Kuśmierski",   gender: "m", image_hash: blobs[23].hash}, 
  { login: "lukowicz",    name: "Mariia Łukowicz",     gender: "f", image_hash: blobs[24].hash}, 
  { login: "mozdzen",     name: "Jarosław Możdżeń",    gender: "m", image_hash: blobs[25].hash}, 
  { login: "zacharczuk",  name: "Wanda Zacharczuk",    gender: "f", image_hash: blobs[26].hash}, 
  { login: "grzelak",     name: "Karol Grzelak",       gender: "m", image_hash: blobs[27].hash}, 
  { login: "wietrzynski", name: "Mariusz Wietrzyński", gender: "m", image_hash: blobs[28].hash},
  { login: "kotecki",     name: "Bogumił Kotecki",     gender: "m", image_hash: blobs[29].hash}, 
]);
